name: publish

on:
  workflow_dispatch:
    inputs:
      publish_npm:
        description: 'Publish to NPM'
        type: boolean
        default: true
        required: false
      create_release:
        description: 'Create GitHub Release & Tag'
        type: boolean
        default: true
        required: false

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: itsferdiardiansa/ci-toolbox/actions/setup-node@v1.0.0

      - name: Build package
        run: pnpm bundle

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  publish-npm:
    name: publish to NPM
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.publish_npm == true && github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: itsferdiardiansa/ci-toolbox/actions/setup-node@v1.0.0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

      - name: Setup NPM Auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: pnpm changeset:publish --cwd dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: create GH release & tag
    runs-on: ubuntu-latest
    if: ${{ always() && inputs.create_release == true && needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    needs: [build, publish-npm]
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: itsferdiardiansa/ci-toolbox/actions/setup-node@v1.0.0
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
      
      - name: Create GitHub Release and Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r .version package.json)
          TAG="v$VERSION"
          
          echo "Preparing release for tag $TAG..."

          TAG_MESSAGE="Bump version to $VERSION. Generated by Github Actions"

          NOTES=$(awk '/^## '$VERSION'/{f=1;next} f==1 && /^## /{f=0} f==1' CHANGELOG.md)
          
          if [ -z "$NOTES" ]; then
            echo "::error::Could not find changelog entry for $VERSION in CHANGELOG.md"
            exit 1
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "$TAG_MESSAGE"
          
          git push origin "$TAG"
          
          echo "$NOTES" | gh release create "$TAG" \
            --title "$TAG" \
            --notes-file -